language: java
jdk:
  - oraclejdk8
script:
  - mvn clean install
notifications:
  email:
    recipients:
      - git@linkedgeodesy.org
    on_success: change
    on_failure: always
addons:
  apt:
    packages:
      - oracle-java8-installer
